version: 2
defaults: &defaults
  docker:
    - image: circleci/php:7.1-apache-node-browsers
  working_directory: ~/web2fs-notepad
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - php-dependencies-{{ checksum "composer.json" }}
            - php-dependencies-
      - restore_cache:
          keys:
            - js-dependencies-{{ checksum "yarn.lock" }}
            - js-dependencies-
      - run: composer install -n --prefer-dist
      - save_cache:
          paths:
            - vendor
          key: php-dependencies-{{ checksum "composer.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: js-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn lint
      - run: ./vendor/bin/phpcs
      - persist_to_workspace:
          root: .
          paths:
            - bin
            - config
            - node_modules
            - public
            - src
            - composer.json
            - composer.lock
            - symfony.lock
            - webpack.config.js
            - package.json
            - tsconfig.json
            - README.md
            - .env.dist
  build:
    <<: *defaults
    environment:
      APP_ENV: prod
    steps:
      - attach_workspace:
          at: .
      - run: composer install --no-dev --prefer-dist --optimize-autoloader
      - run: yarn build
      - run: tar
          --ignore-case --exclude 'vendor/*/tests' --exclude 'vendor/*.md' --exclude 'vendor/*.gitignore' --exclude 'vendor/*/LICENSE*'
          -cvzf dist.tar.gz
          config/ public/ vendor/ bin/ src/ .env.dist README.md
      - store_artifacts:
          path: dist.tar.gz
workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - build:
          requires:
            - test
