parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{NoteStore,Kernel.php}'
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
