services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\:
    resource: '../src/*'
    exclude: '../src/Kernel.php'

  App\Controller:
    tags:
      - { name: kernel.event_listener, event: kernel.exception }
